### ISSUE TITLE
Game progress can't be saved.

### ISSUE THREAD

**Issue by LunAhEric** [FirehawkV21/RMMVCookTool#93]
![image](https://github.com/FirehawkV21/RMMVCookTool/assets/94828018/b8542445-51db-415f-b6e4-35759fcbdf1b)

After using package.nw, the game progress cannot be saved even while playing the game.
Don't know how to fix it.
Thanks

**Comment by FirehawkV21** [comment]
Hello,

This is a quirk with the engine, as it uses the game's location for saving. And since nwjs deletes the temp folder (as it decompresses the package.nw in order to start the game) it deletes them. The only fix that is possible is to use a plugin that changes the location of the saves.
